// 애플리케이션 에러 코드 상수
module.exports = Object.freeze({
  MISSING_FIELD: 'MISSING_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  EMAIL_DUPLICATE: 'EMAIL_DUPLICATE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CATEGORY_NAME_DUPLICATE: 'CATEGORY_NAME_DUPLICATE',
  TODO_FORBIDDEN: 'TODO_FORBIDDEN',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
});
